enum {
	EMPEROR = 0,
	HERO = 1,
	PLOY = 2,
	ARTIFACT = 3,
	SPELL = 4
}
enum {
	LP = 1,
}
const atlas_path = {
	LP = "res://Assets/CardAtlas/LostParadiseUnitAtlas.tres",
}
const CARDS = { #Attack,Health,#ApCost,#Type #AtlasRegion #Faction
	# TYPE [ 0 = Emperor, 1 = Hero , 2 = Ploy , 3 = Artifact, 4 = Spell
	#"Sample": {
		#"attack": 1,
		#"health": 1,
		#"apCost": 0,
		#"type": HERO,
		#"atlasRegion": [0,0,207,252],
		#"atlasPath": atlas_path.NEUTRAL_1,
		#"faction": NEUTRAL,
		#"moveRange": 1,
		#"attackRange": 1
	#},
	"Emperor of Lost Paradise": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Fog Raven": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Curse": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Soul Smasher": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Evil Murmur": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Asmodeus": {
		"attack": 2,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Beelzebub": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dumuzid": {
		"attack": 5,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Snowy Salutation": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sumptuous Summer": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Girl Next Door": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mirror Familiars": {
		"attack": 0,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Frog": {
		"attack": 1,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Demon": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ashmodai": {
		"attack": 2,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Insane Contract": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Soul Freeze": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Cursed Mirror": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hallucination": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Odd Cube": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mastema": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Shadow Contract": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Gospel": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Daagon": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Leviathan": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Fair Trade": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Azrael": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Belphegor": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Abadon": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mammon": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mutating Poison": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Adrammelech": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mad Nightmare": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Belial": {
		"attack": 1,
		"health": 1,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Samael": {
		"attack": 5,
		"health": 7,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Purge": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Grim Reaper": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sacrificial Heal": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Blood Offering": {
		"attack": 0,
		"health": 0,
		"apCost": 7,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Lucifer": {
		"attack": 5,
		"health": 5,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dice": {
		"attack": 1,
		"health": 1,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Astaroth": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Forbidden Fruit": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sion": {
		"attack": 4,
		"health": 3,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Degenerate": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Satan": {
		"attack": 6,
		"health": 6,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Pipedream Reverb": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Moloch": {
		"attack": 1,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Double-Edged Sword": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Chemosh": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Remmon": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Abdiel": {
		"attack": 3,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nisroch": {
		"attack": 3,
		"health": 5,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Vicious Wish": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ariel": {
		"attack": 4,
		"health": 3,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mulciber": {
		"attack": 6,
		"health": 8,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
}
