enum {
	EMPEROR = 0,
	HERO = 1,
	PLOY = 2,
	ARTIFACT = 3,
	SPELL = 4
}
enum {
	LP = 1,
}
const atlas_path = {
	LP = "res://Assets/CardAtlas/LostParadiseUnitAtlas.tres",
}
const CARDS = { #Attack,Health,#ApCost,#Type #AtlasRegion #Faction
	# TYPE [ 0 = Emperor, 1 = Hero , 2 = Ploy , 3 = Artifact, 4 = Spell
	#"Sample": {
		#"attack": 1,
		#"health": 1,
		#"apCost": 0,
		#"type": HERO,
		#"atlasRegion": [0,0,207,252],
		#"atlasPath": atlas_path.NEUTRAL_1,
		#"faction": NEUTRAL,
		#"moveRange": 1,
		#"attackRange": 1
	#},
	"실낙원 군주": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"포그 레이븐": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"저주": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"영혼 파괴자": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"악마의 속삭임": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아스모데우스": {
		"attack": 2,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"벨제붑": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"두무지": {
		"attack": 5,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"눈과 얼음의 인사": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"찬란한 여름": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"이웃집 여동생": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"사역마": {
		"attack": 0,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"개구리": {
		"attack": 1,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"악마": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"저주：마비": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"저주：수면": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"저주：족쇄": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"저주：실명": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아쉬모다이": {
		"attack": 2,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"광기의 계약": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"영혼 빙결": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"저주받은 거울": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"환영": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"차단장벽": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"마스테마": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"암흑 계약": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"복음서": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"다곤": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"레비아탄": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"등가교환": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아즈라엘": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"벨페고르": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아바돈": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"마몬": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"변신 물약": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아드람멜렉": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"광기의 악몽": {
		"attack": 0,
		"health": 0,
		"apCost": 7,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"벨리알": {
		"attack": 1,
		"health": 1,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"사마엘": {
		"attack": 5,
		"health": 7,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"지옥의 업화": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"사망 선고": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"치명상 치료": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"루시퍼": {
		"attack": 5,
		"health": 5,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"다이스": {
		"attack": 1,
		"health": 1,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아스타로드": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"금지된 과일": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"시온": {
		"attack": 4,
		"health": 3,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"타락": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"사탄": {
		"attack": 6,
		"health": 6,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"꿈의 메아리": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"몰렉": {
		"attack": 1,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"양날검": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"키마슈": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"임문": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"압디엘": {
		"attack": 3,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"니스록": {
		"attack": 3,
		"health": 5,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"배덕의 기원": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"아리": {
		"attack": 4,
		"health": 3,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"마르시바": {
		"attack": 6,
		"health": 8,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
}
