enum {
	EMPEROR = 0,
	HERO = 1,
	PLOY = 2,
	ARTIFACT = 3,
	SPELL = 4
}
enum {
	LP = 1,
}
const atlas_path = {
	LP = "res://Assets/CardAtlas/LostParadiseUnitAtlas.tres",
}

const CARDS = { #Attack,Health,#ApCost,#Type #AtlasRegion #Faction
	# TYPE [ 0 = Emperor, 1 = Hero , 2 = Ploy , 3 = Artifact, 4 = Spell
	#"Sample": {
		#"attack": 1,
		#"health": 1,
		#"apCost": 0,
		#"type": HERO,
		#"atlasRegion": [0,0,207,252],
		#"atlasPath": atlas_path.NEUTRAL_1,
		#"faction": NEUTRAL,
		#"moveRange": 1,
		#"attackRange": 1
	#},
	"失楽園君主": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"失乐园君主": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"失樂園君主": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"霧のレイヴン": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"迷雾乌鸦": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"迷霧烏鴉": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"呪い": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"诅咒": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"詛咒": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ソウルクラッシャー": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"灵魂破碎": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"靈魂破碎": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"悪魔のささやき": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"邪魔低语": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"邪魔低語": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アスモデウス": {
		"attack": 2,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"阿斯莫德": {
		"attack": 2,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ベルゼブブ": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"别西卜": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"別西卜": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"タンムーズ": {
		"attack": 5,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"塔姆斯": {
		"attack": 5,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"氷雪のあいさつ": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"冰与雪的问候": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"冰與雪的問候": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"艶やかな夏": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"缤纷娇夏": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"繽紛嬌夏": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"近所の女の子": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"邻家小妹": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"鄰家小妹": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"鏡のスピリット": {
		"attack": 0,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"镜像使魔": {
		"attack": 0,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"鏡像使魔": {
		"attack": 0,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"カエル": {
		"attack": 1,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"青蛙": {
		"attack": 1,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"悪魔": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"恶魔": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"惡魔": {
		"attack": 6,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"呪い：麻痺": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"诅咒：麻痹": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"詛咒：麻痺": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"呪い：睡眠": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"诅咒：睡眠": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"詛咒：睡眠": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"呪い：足止め": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"诅咒：禁足": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"詛咒：禁足": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"呪い：暗闇": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"诅咒：致盲": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"詛咒：致盲": {
		"attack": 0,
		"health": 0,
		"apCost": 1,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アスモダイ": {
		"attack": 2,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"阿斯玛代": {
		"attack": 2,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"阿斯瑪代": {
		"attack": 2,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"狂気の契約": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"疯狂契约": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"瘋狂契約": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ソウルフリーズ": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"灵魂冻结": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"靈魂凍結": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"呪われた鏡": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"折光棱镜": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"折光棱鏡": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"幻覚": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"幻象": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"バリア": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"遮断屏障": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"遮斷屏障": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"マスティマ": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"莫斯提马": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"莫斯提馬": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"暗黒契約": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"暗影契约": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"暗影契約": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"福音書": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"福音法典": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ダーゴン": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"大衮": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"大袞": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"レヴィアタン": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"利维坦": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"利維坦": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"等価交換": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"等价交换": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"等價交換": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アザゼル": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"阿撒兹勒": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"阿撒茲勒": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ベルフェゴール": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"贝尔芬格": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"貝爾芬格": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アバドン": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亚巴顿": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亞巴頓": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"マモン": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"玛门": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"瑪門": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"変異毒": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"变形毒药": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"變形毒藥": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アドラメレク": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亚得米勒": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亞得米勒": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"狂気の悪夢": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"狂乱梦魇": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"狂亂夢魘": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ベリアル": {
		"attack": 1,
		"health": 1,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"彼列": {
		"attack": 1,
		"health": 1,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"サマエル": {
		"attack": 5,
		"health": 7,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"萨麦尔": {
		"attack": 5,
		"health": 7,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"薩麥爾": {
		"attack": 5,
		"health": 7,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"地獄の業火": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"炼狱业火": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"煉獄業火": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"死の宣告": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"死亡宣告": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"瀉血療法": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"致命治疗": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"致命治療": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"血の奉納": {
		"attack": 0,
		"health": 0,
		"apCost": 7,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"鲜血献祭": {
		"attack": 0,
		"health": 0,
		"apCost": 7,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"鮮血獻祭": {
		"attack": 0,
		"health": 0,
		"apCost": 7,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ルシファー": {
		"attack": 5,
		"health": 5,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"路西法": {
		"attack": 5,
		"health": 5,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"デイズ": {
		"attack": 1,
		"health": 1,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"戴斯": {
		"attack": 1,
		"health": 1,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アスタロト": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亚斯托勒": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亞斯托勒": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"いけない果実": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"禁忌果实": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"禁忌果實": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"シオン": {
		"attack": 4,
		"health": 3,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"塞恩": {
		"attack": 4,
		"health": 3,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"賽恩": {
		"attack": 4,
		"health": 3,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"堕落": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"墮落": {
		"attack": 0,
		"health": 0,
		"apCost": 5,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"サタン": {
		"attack": 6,
		"health": 6,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"撒旦": {
		"attack": 6,
		"health": 6,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"迷夢の反響": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"迷梦回声": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"迷夢迴聲": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"モロ": {
		"attack": 1,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"摩洛": {
		"attack": 1,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"両刃の剣": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"双刃剑": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"雙刃劍": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ケモシュ": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"基抹": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ラモン": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"临门": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"臨門": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アブディエル": {
		"attack": 3,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亚必迭": {
		"attack": 3,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亞必迭": {
		"attack": 3,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ニスロク": {
		"attack": 3,
		"health": 5,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"尼斯洛": {
		"attack": 3,
		"health": 5,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"祈願の背徳": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"背德祈愿": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"背德祈願": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"アリエル": {
		"attack": 4,
		"health": 3,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亚利": {
		"attack": 4,
		"health": 3,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"亞利": {
		"attack": 4,
		"health": 3,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"ムルキベル": {
		"attack": 6,
		"health": 8,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"玛尔西巴": {
		"attack": 6,
		"health": 8,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
	"瑪爾西巴": {
		"attack": 6,
		"health": 8,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0, 0, 207, 252],
		"atlasPath": atlas_path.LP,
		"faction": LP,
		"moveRange": 1,
		"attackRange": 1
	},
}
