enum {
	EMPEROR = 0,
	HERO = 1,
	PLOY = 2,
	ARTIFACT = 3,
	SPELL = 4
}
enum {
	NEUTRAL = 0,
}
const atlas_path = {
	ARTIFACT ="res://Assets/CardAtlas/ArtifactAtlas.tres",
	NEUTRAL_1 ="res://Assets/CardAtlas/Neutral1UnitAtlas.tres",
	NEUTRAL_2 = "res://Assets/CardAtlas/Neutral2UnitAtlas2.tres",
	SPELL_1 = "res://Assets/CardAtlas/SpellAtlas.tres",
	SPELL_2 = "res://Assets/CardAtlas/SpellAtlas2.tres",
	SPELL_3 = "res://Assets/CardAtlas/SpellAtlas3.tres",
}

const CARDS = { #Attack,Health,#ApCost,#Type #AtlasRegion #Faction
	# TYPE [ 0 = Emperor, 1 = Hero , 2 = Ploy , 3 = Artifact, 4 = Spell
	#"Sample": {
		#"attack": 1,
		#"health": 1,
		#"apCost": 0,
		#"type": HERO,
		#"atlasRegion": [0,0,207,252],
		#"atlasPath": atlas_path.NEUTRAL_1,
		#"faction": NEUTRAL,
		#"moveRange": 1,
		#"attackRange": 1
	#},
	"Hai Uri": {
		"attack": 1,
		"health": 1,
		"apCost": 0,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Karuhaimu": {
		"attack": 1,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Beng": {
		"attack": 1,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Baba Yaga": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Fene": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Jall": {
		"attack": 2,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Utukku": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hera": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Pulgasari": {
		"attack": 2,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Jahi": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dokkaebi": {
		"attack": 3,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Yongkuei": {
		"attack": 4,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Lamastu": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Enoch": {
		"attack": 4,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Bilwis": {
		"attack": 5,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dimme": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Puck": {
		"attack": 4,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Aigamuxa": {
		"attack": 5,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Apaosha": {
		"attack": 3,
		"health": 4,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sri": {
		"attack": 6,
		"health": 7,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Matuku": {
		"attack": 9,
		"health": 9,
		"apCost": 10,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Belief Crystal": {
		"attack": 0,
		"health": 0,
		"apCost": 0,
		"type": SPELL,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Tear": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": ARTIFACT,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Camazotz": {
		"attack": 2,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sabina": {
		"attack": 3,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Shutu": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sappo Feruso": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Randa": {
		"attack": 4,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Vodnik": {
		"attack": 5,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ispusteke": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Bushasp": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dud": {
		"attack": 2,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ixtab": {
		"attack": 2,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Waillepen": {
		"attack": 4,
		"health": 2,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mahr": {
		"attack": 4,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Edimmu": {
		"attack": 6,
		"health": 4,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Koshchei": {
		"attack": 5,
		"health": 7,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Giribito": {
		"attack": 6,
		"health": 9,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nesyutepewa": {
		"attack": 6,
		"health": 5,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Jarri (Clown)": {
		"attack": 5,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ereshkigal (Bride)": {
		"attack": 6,
		"health": 6,
		"apCost": 10,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Misfit": {
		"attack": 2,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Aesma": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Inguma": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Drud": {
		"attack": 3,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Puppeteer: Happy": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Wizard: Cid": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ploy Master: Phil": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Blacksmith: Engel": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Iya": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Irad": {
		"attack": 2,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Sta Au": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Torto": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Agas": {
		"attack": 3,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Buau": {
		"attack": 3,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Chert": {
		"attack": 2,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Besu": {
		"attack": 4,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Vetehinen": {
		"attack": 2,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Rokita": {
		"attack": 2,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Chonchon": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Tursas": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Oke": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dera Buranka": {
		"attack": 2,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Vanth": {
		"attack": 2,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Erzulie Dantor": {
		"attack": 2,
		"health": 4,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nintu": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Pairilas": {
		"attack": 2,
		"health": 6,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Diwe": {
		"attack": 4,
		"health": 2,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Dullahan": {
		"attack": 4,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Incubus": {
		"attack": 3,
		"health": 2,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Succubus": {
		"attack": 2,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Erge": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Etemmu": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Cherufe": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Drug": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Buruke": {
		"attack": 3,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Befana": {
		"attack": 5,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Jarri": {
		"attack": 4,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Itzam Cab Ain": {
		"attack": 4,
		"health": 4,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Lioumere": {
		"attack": 5,
		"health": 2,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kunda": {
		"attack": 5,
		"health": 7,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Eratemu": {
		"attack": 4,
		"health": 3,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Erra": {
		"attack": 5,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kalma": {
		"attack": 5,
		"health": 4,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Legba": {
		"attack": 4,
		"health": 4,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Culsu": {
		"attack": 3,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Orphidon": {
		"attack": 4,
		"health": 4,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ljubi": {
		"attack": 4,
		"health": 4,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Grendel": {
		"attack": 4,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Heros": {
		"attack": 4,
		"health": 2,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Zu": {
		"attack": 5,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Alardi": {
		"attack": 5,
		"health": 4,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Boruta": {
		"attack": 5,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Loco": {
		"attack": 5,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mulla": {
		"attack": 6,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Citipati": {
		"attack": 4,
		"health": 6,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Otso": {
		"attack": 5,
		"health": 4,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Mot": {
		"attack": 4,
		"health": 2,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Paracelsus": {
		"attack": 6,
		"health": 5,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Asto Vidatu": {
		"attack": 6,
		"health": 6,
		"apCost": 7,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kukulkan": {
		"attack": 7,
		"health": 6,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ereshkigal": {
		"attack": 5,
		"health": 5,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Cain": {
		"attack": 10,
		"health": 10,
		"apCost": 10,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Tawiskala": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Simbacher": {
		"attack": 6,
		"health": 6,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Chiron": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kairos": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Jehu": {
		"attack": 6,
		"health": 5,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Puadotaci": {
		"attack": 6,
		"health": 8,
		"apCost": 8,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	},
	"Elel": {
		"attack": 7,
		"health": 7,
		"apCost": 9,
		"type": HERO,
		"atlasRegion": [0,0,207,252,],
		"atlasPath": atlas_path.NEUTRAL_1,
		"faction": NEUTRAL,
		"moveRange": 1,
		"attackRange": 1
	}
}
