enum {
	EMPEROR = 0,
	HERO = 1,
	PLOY = 2,
	ARTIFACT = 3,
	SPELL = 4
}
enum {
	ONMYODO = 3,
}
const atlas_path = {
	ARTIFACT ="res://Assets/CardAtlas/ArtifactAtlas.tres",
	ONMYODO_1 = "res://Assets/CardAtlas/OnmyodoUnitAtlas1.tres",
	ONMYODO_2 = "res://Assets/CardAtlas/OnmyodoUnitAtlas2.tres",
	SKIN = "res://Assets/CardAtlas/SkinListAtlas.tres",
	SPELL_1 = "res://Assets/CardAtlas/SpellAtlas.tres",
	SPELL_2 = "res://Assets/CardAtlas/SpellAtlas2.tres",
	SPELL_3 = "res://Assets/CardAtlas/SpellAtlas3.tres",
}

const CARDS = { #Attack,Health,#ApCost,#Type #AtlasRegion #Faction
	# TYPE [ 0 = Emperor, 1 = Hero , 2 = Ploy , 3 = Artifact, 4 = Spell
	#"Sample": {
		#"attack": 1,
		#"health": 1,
		#"apCost": 0,
		#"type": HERO,
		#"atlasRegion": [0,0,207,252],
		#"atlasPath": atlas_path.NEUTRAL_1,
		#"faction": NEUTRAL,
		#"moveRange": 1,
		#"attackRange": 1
	#},
	"Emperor of Onmyodo": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Aoandon": {
		"attack": 2,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ao-Oni": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Aka-Oni": {
		"attack": 1,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Spirit Spear": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": ARTIFACT,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hannya": {
		"attack": 3,
		"health": 1,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Trinity of Souls": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Midsummer Promise": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nighty Ninja": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Innocent Fox": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Glorious Summer": {
		"attack": 0,
		"health": 20,
		"apCost": 0,
		"type": EMPEROR,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kouyouki": {
		"attack": 3,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Umi-Yurei": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Katakirauwa": {
		"attack": 0,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Tamamo-no-Mae": {
		"attack": 1,
		"health": 1,
		"apCost": 9,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hiyo": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Goriki Oni": {
		"attack": 5,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kitsunebi": {
		"attack": 1,
		"health": 3,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"God of Thunder": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kappa": {
		"attack": 2,
		"health": 1,
		"apCost": 1,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nekomata": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Onikiri": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Futakuchi-onna": {
		"attack": 2,
		"health": 2,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ceremony Ploy": {
		"attack": 0,
		"health": 8,
		"apCost": 2,
		"type": "PLOY",
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ameonna": {
		"attack": 2,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kasha": {
		"attack": 3,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Momijigari": {
		"attack": 1,
		"health": 1,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Rokurokubi": {
		"attack": 2,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ibaraki Douji": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Yuki-onna": {
		"attack": 4,
		"health": 2,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kurozuka": {
		"attack": 2,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Heavenly Pass": {
		"attack": 0,
		"health": 0,
		"apCost": 3,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Enma": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Tengu Feathers": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": ARTIFACT,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hashihime": {
		"attack": 0,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Psychic Bind": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Onihitokuchi": {
		"attack": 2,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Murder Ritual": {
		"attack": 0,
		"health": 0,
		"apCost": 6,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Shuten Douji": {
		"attack": 4,
		"health": 1,
		"apCost": 9,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Oitekebori": {
		"attack": 2,
		"health": 1,
		"apCost": 2,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Monster's blood": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Ghost curse": {
		"attack": 0,
		"health": 0,
		"apCost": 2,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Wanyudo": {
		"attack": 2,
		"health": 1,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Yamauba": {
		"attack": 3,
		"health": 3,
		"apCost": 3,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Zashiki Warashi": {
		"attack": 3,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hone Onna": {
		"attack": 3,
		"health": 4,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Summoned Wrath": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Monster Ball": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nure Onna": {
		"attack": 2,
		"health": 2,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Nurarihyon": {
		"attack": 5,
		"health": 5,
		"apCost": 5,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Spirit Liberation": {
		"attack": 0,
		"health": 0,
		"apCost": 0,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"100 Evils": {
		"attack": 0,
		"health": 0,
		"apCost": 0,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Barren Bones": {
		"attack": 0,
		"health": 2,
		"apCost": 2,
		"type": "PLOY",
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Soul Chariot": {
		"attack": 0,
		"health": 3,
		"apCost": 3,
		"type": "PLOY",
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Kiyohime": {
		"attack": 3,
		"health": 5,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Yao-Hu": {
		"attack": 4,
		"health": 3,
		"apCost": 4,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Naruto": {
		"attack": 0,
		"health": 0,
		"apCost": 4,
		"type": SPELL,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Enenra": {
		"attack": 6,
		"health": 4,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	},
	"Hinoenma": {
		"attack": 4,
		"health": 3,
		"apCost": 6,
		"type": HERO,
		"atlasRegion": [0,0,207,252],
		"atlasPath": atlas_path.ONMYODO_1,
		"faction": ONMYODO,
		"moveRange": 1,
		"attackRange": 1
	}
}
